### ISSUE TITLE
Erneutes Hochladen von Units: Status unklar

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-player-testbed#10]
- Werden alte Units ersetzt?
- Was ist mit den gegebenen Antworten. Sollte alles entfernt werden.

**Comment by mechtelm** [comment]
Beim Löschen des Unit-Stacks sollten alle Antworten gelöscht werden. Beim Überschreiben einer schon geladenen Unit (gleicher Dateiname) sollten die Antworten ebenfalls gelöscht werden, da z. B. nicht klar ist, ob die neuen Variablen andere Datentypen haben.
