### ISSUE TITLE
Darstellen von Antworten

### ISSUE THREAD

**Issue by jojohoch** [iqb-berlin/verona-player-testbed#15]
Eine  `vopStateChangedNotification` deren `unitstate`  `dataParts` beinhaltete, hält in der Property `unitStateDataType` Informationen über deren Format bereit.  Wie soll das VeronaTestBed mit diesen Informationen verfahren?

**Comment by mechtelm** [comment]
In einer späteren Version sollten die Antworten übersichtlich dargestellt werden, jedenfalls bei bekannten unitStateDataType.
