### ISSUE TITLE
Navigation nur in Abhängigkeit von reponseProgress erlauben

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/verona-player-testbed#4]
Interessant wäre ein Modus, in dem Navigation zur nächsten Unit nur erlaubt wird, wenn `reponseProgress`= `complete`  oder `complete-and-valid` ist. Der Dan-Player unterstützt keine Validierung, hier wäre `complete` also das höchste was man erreichen kann. 

s. a.:
* https://github.com/verona-interfaces/player/blob/master/api/asyncapi.md#publish-vopstartcommand
* https://github.com/verona-interfaces/player/issues/25

**Comment by mechtelm** [comment]
Mit der Verona-Spec 2.2 ist das notwendig: Das Testbed schickt `vopNavigationDeniedNotification` und löst damit z. B. das markAllAsTouched aus!

**Comment by paflov** [comment]
Ja. Was mit jetzt gerade unklar ist, was ich mir exakt vorstellte, was das für das TestBed bedeutet. Ich denke das Ticket kann geschlossen werden, ist ja mit verbauen der neuen Verona-Version eigentlich abgedeckt.
