### ISSUE TITLE
implement vopUnitNavigationRequestedNotification

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/verona-player-testbed#5]
https://github.com/iqb-berlin/verona-player-testbed/blob/938201f380da45109e2085d28445a72ac9a24fa5/src/app/unit-host/unit-host.component.ts#L410

Neben den Navigationsbutton in Unit-HOST können auch Unit-Navigations-Buttons im Player verbaut werden. Da die einzelne Unit den Aufbau des Testhefts nicht kennt, sind hier nur benannte Zeile möglich: ´#next´, ´#previous´, ´#first´, ´#last´.
Siehe:
* https://github.com/verona-interfaces/player/blob/master/api/asyncapi.md#subscribe-vopunitnavigationrequestednotification
* Achtung, Doku stimmt hier nicht: https://github.com/verona-interfaces/player/issues/22

Daneben sieht Verona2 noch ein weiteres benanntes Zeil vor: `#end`. Das beendet das Testheft. Im Testbed hieße das wohl, dass man wieder auf den StartBildschirm zurückkommt? 

Nebenbei gesagt: Das Test*center* kennt noch weitere benannte Ziele, z. B. `#menu`; diese sind jedoch nicht Verona2-Standart und haben fürs Testbed keine relevanz. So ist es im Testcenter gelöst:
* https://github.com/iqb-berlin/testcenter-frontend/blob/17e9372e9d43e00a1ba68704ac2af8a3746f1e90/src/app/test-controller/test-controller.service.ts#L311

**Comment by mechtelm** [comment]
Das Testbed sollte nicht nur auf die Console ausgeben, sondern auch navigieren. `end` wäre für die Home-Page.

Das Testcenter hat zwar noch weitere Sprungziele, die sind aber nicht für den Player vorgesehen.

Bitte Sprungmarken ohne Hash-Zeichen implementieren (so wie in Verona-Spec).
