### ISSUE TITLE
Data chunks implementieren

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/verona-player-testbed#7]
Die Definition der Verona Schnittstelle sieht die Aufteilung der Antwort-Daten vor (referenziert über Schlüssel). Das Testbed sollte das unterstützen. Hierzu sind pro Unit im lokalen Zwischenspeicher (TestControllerService -> setResponsesStatus) nur die Daten-Chunks zu ersetzen, die bei `vopStateChangedNotification` bzw. `vopGetStateResponse` geschickt wurden.

Leider gibt es derzeit keinen Player, der mehr als einen Daten-Chunk schickt.

**Comment by rhenck** [comment]
Nur synchron mit a) Testcenter und mit b) Dan-Player (und Teststudio). Müsste alles gleichzeitig passieren.

**Comment by mechtelm** [comment]
Verona 5 ist im Prinzip umgesetzt, d. h. data chunks werden auch so weggespeichert. Allerdings gibt es noch keinen Mechanismus für den Fall, dass verschiedene chunks zu unterschiedlichen Zeitpunkten geschickt werden. Aspect wird das demnächst implementieren (GeoGebra!). Dann kann man zwar in der Konsole das Schicken beobachten, die Wiederherstellung beim Zurückblättern glückt dann aber nur für den zuletzt geschickten chunk.

Übrigens ist das Testcenter schon umgestellt, hier läuft das korrekt.
